[project]
name = "simple_experiment"
version = "0.1.0"
requires-python = ">=3.10,<3.14"
dependencies = ["pandas","matplotlib","tqdm","scikit-learn","scikit-image","pyyaml","opencv-python","seaborn","tabulate","requests","mlflow>=2.13.0,<3.0.0","pyarrow>=15.0.0"]

[tool.uv]
package = true